-- Complete location mapping from your archipelago.lua
LOCATION_TO_TRACKER_MAP = {
    -- =====================================
    -- EVENT MATCHES
    -- =====================================
    [0xF9] = "@Event Matches/Event Match 1-10/Bomb-fest",
    [0x104] = "@Event Matches/Event Match 11-15/Trophy Tussle 1",
    [0x110] = "@Event Matches/Event Match 21-30/Trophy Tussle 2",
    [0x123] = "@Event Matches/Event Match 40-50/Game & Watch Forever!",
    [0x125] = "@Event Matches/Event Match 40-50/Trophy Tussle 3",
    [0x129] = "@Event Matches/Event Match 51/The Showdown",

    -- Additional Event Matches (when event_checks enabled)
    [0xF7] = "@Event Matches/Event Match 1-10/Trouble King",
    [0xF8] = "@Event Matches/Event Match 1-10/Lord of the Jungle",
    [0xFA] = "@Event Matches/Event Match 1-10/Dino-wrangling",
    [0xFB] = "@Event Matches/Event Match 1-10/Spare Change",
    [0xFC] = "@Event Matches/Event Match 1-10/Kirbys on Parade",
    [0xFD] = "@Event Matches/Event Match 1-10/Pokémon Battle",
    [0xFE] = "@Event Matches/Event Match 1-10/Hot Date on Brinstar",
    [0xFF] = "@Event Matches/Event Match 1-10/Hide'n' Sheik",
    [0x100] = "@Event Matches/Event Match 1-10/All-Star Match 1",
    [0x101] = "@Event Matches/Event Match 11-15/King of the Mountain",
    [0x102] = "@Event Matches/Event Match 11-15/Seconds, Anyone?",
    [0x103] = "@Event Matches/Event Match 11-15/Yoshi's Egg",
    [0x105] = "@Event Matches/Event Match 11-15/Girl Power",
    [0x106] = "@Event Matches/Event Match 16-20/Kirby's Air-raid",
    [0x107] = "@Event Matches/Event Match 16-20/Bounty Hunters",
    [0x108] = "@Event Matches/Event Match 16-20/Link's Adventure",
    [0x109] = "@Event Matches/Event Match 16-20/Peach's Peril",
    [0x10A] = "@Event Matches/Event Match 16-20/All-Star Match 2",
    [0x10B] = "@Event Matches/Event Match 21-30/Ice Breaker",
    [0x10C] = "@Event Matches/Event Match 21-30/Super Mario 128",
    [0x10D] = "@Event Matches/Event Match 21-30/Slippy's Invention",
    [0x10E] = "@Event Matches/Event Match 21-30/The Yoshi Herd",
    [0x10F] = "@Event Matches/Event Match 21-30/Gargantuans",
    [0x111] = "@Event Matches/Event Match 21-30/Cold Armor",
    [0x112] = "@Event Matches/Event Match 21-30/Puffballs Unite!",
    [0x113] = "@Event Matches/Event Match 21-30/Triforce Gathering",
    [0x114] = "@Event Matches/Event Match 21-30/All-Star Match 3",
    [0x115] = "@Event Matches/Event Match 31-39/Mario Bros. Madness",
    [0x116] = "@Event Matches/Event Match 31-39/Target Acquired",
    [0x117] = "@Event Matches/Event Match 31-39/Lethal Marathon",
    [0x118] = "@Event Matches/Event Match 31-39/Seven Years",
    [0x119] = "@Event Matches/Event Match 31-39/Time for a Checkup",
    [0x11A] = "@Event Matches/Event Match 31-39/Space Travelers",
    [0x11B] = "@Event Matches/Event Match 31-39/Legendary Pokémon",
    [0x11C] = "@Event Matches/Event Match 31-39/Super Mario Bros. 2",
    [0x11D] = "@Event Matches/Event Match 31-39/Jigglypuff Live!",
    [0x11E] = "@Event Matches/Event Match 40-50/All-Star Match 4",
    [0x11F] = "@Event Matches/Event Match 40-50/En Garde!",
    [0x120] = "@Event Matches/Event Match 40-50/Trouble King 2",
    [0x121] = "@Event Matches/Event Match 40-50/Birds of Prey",
    [0x122] = "@Event Matches/Event Match 40-50/Mewtwo Strikes!",
    [0x124] = "@Event Matches/Event Match 40-50/Fire Emblem Pride",
    [0x126] = "@Event Matches/Event Match 40-50/Pikachu and Pichu",
    [0x127] = "@Event Matches/Event Match 40-50/All-Star Match Deluxe",
    [0x128] = "@Event Matches/Event Match 40-50/Final Destination Match",

    -- =====================================
    -- CHARACTER TROPHIES
    -- =====================================
    -- Adventure Mode Trophies
    [0x12A] = "@Character Trophies/Adventure Mode Trophies/Mario - Adventure Trophy",
    [0x12B] = "@Character Trophies/Classic Mode Trophies/Mario - Classic Trophy",
    [0x12C] = "@Character Trophies/All-Star Mode Trophies/Mario - All-Star Trophy",
    [0x12D] = "@Character Trophies/Adventure Mode Trophies/Donkey Kong - Adventure Trophy",
    [0x12E] = "@Character Trophies/Classic Mode Trophies/Donkey Kong - Classic Trophy",
    [0x12F] = "@Character Trophies/All-Star Mode Trophies/Donkey Kong - All-Star Trophy",
    [0x130] = "@Character Trophies/Adventure Mode Trophies/Link - Adventure Trophy",
    [0x131] = "@Character Trophies/Classic Mode Trophies/Link - Classic Trophy",
    [0x132] = "@Character Trophies/All-Star Mode Trophies/Link - All-Star Trophy",
    [0x133] = "@Character Trophies/Adventure Mode Trophies/Samus - Adventure Trophy",
    [0x134] = "@Character Trophies/Classic Mode Trophies/Samus - Classic Trophy",
    [0x135] = "@Character Trophies/All-Star Mode Trophies/Samus - All-Star Trophy",
    [0x136] = "@Character Trophies/Adventure Mode Trophies/Yoshi - Adventure Trophy",
    [0x137] = "@Character Trophies/Classic Mode Trophies/Yoshi - Classic Trophy",
    [0x138] = "@Character Trophies/All-Star Mode Trophies/Yoshi - All-Star Trophy",
    [0x139] = "@Character Trophies/Adventure Mode Trophies/Kirby - Adventure Trophy",
    [0x13A] = "@Character Trophies/Classic Mode Trophies/Kirby - Classic Trophy",
    [0x13B] = "@Character Trophies/All-Star Mode Trophies/Kirby - All-Star Trophy",
    [0x13C] = "@Character Trophies/Adventure Mode Trophies/Fox - Adventure Trophy",
    [0x13D] = "@Character Trophies/Classic Mode Trophies/Fox - Classic Trophy",
    [0x13E] = "@Character Trophies/All-Star Mode Trophies/Fox - All-Star Trophy",
    [0x13F] = "@Character Trophies/Adventure Mode Trophies/Pikachu - Adventure Trophy",
    [0x140] = "@Character Trophies/Classic Mode Trophies/Pikachu - Classic Trophy",
    [0x141] = "@Character Trophies/All-Star Mode Trophies/Pikachu - All-Star Trophy",
    [0x142] = "@Character Trophies/Adventure Mode Trophies/Ness - Adventure Trophy",
    [0x143] = "@Character Trophies/Classic Mode Trophies/Ness - Classic Trophy",
    [0x144] = "@Character Trophies/All-Star Mode Trophies/Ness - All-Star Trophy",
    [0x145] = "@Character Trophies/Adventure Mode Trophies/Captain Falcon - Adventure Trophy",
    [0x146] = "@Character Trophies/Classic Mode Trophies/Captain Falcon - Classic Trophy",
    [0x147] = "@Character Trophies/All-Star Mode Trophies/Captain Falcon - All-Star Trophy",
    [0x148] = "@Character Trophies/Adventure Mode Trophies/Bowser - Adventure Trophy",
    [0x149] = "@Character Trophies/Classic Mode Trophies/Bowser - Classic Trophy",
    [0x14A] = "@Character Trophies/All-Star Mode Trophies/Bowser - All-Star Trophy",
    [0x14B] = "@Character Trophies/Adventure Mode Trophies/Peach - Adventure Trophy",
    [0x14C] = "@Character Trophies/Classic Mode Trophies/Peach - Classic Trophy",
    [0x14D] = "@Character Trophies/All-Star Mode Trophies/Peach - All-Star Trophy",
    [0x14E] = "@Character Trophies/Adventure Mode Trophies/Ice Climbers - Adventure Trophy",
    [0x14F] = "@Character Trophies/Classic Mode Trophies/Ice Climbers - Classic Trophy",
    [0x150] = "@Character Trophies/All-Star Mode Trophies/Ice Climbers - All-Star Trophy",
    [0x151] = "@Character Trophies/Adventure Mode Trophies/Zelda - Adventure Trophy",
    [0x152] = "@Character Trophies/Classic Mode Trophies/Zelda - Classic Trophy",
    [0x153] = "@Character Trophies/All-Star Mode Trophies/Zelda - All-Star Trophy",
    [0x154] = "@Character Trophies/Adventure Mode Trophies/Sheik - Adventure Trophy",
    [0x155] = "@Character Trophies/Classic Mode Trophies/Sheik - Classic Trophy",
    [0x156] = "@Character Trophies/All-Star Mode Trophies/Sheik - All-Star Trophy",
    [0x157] = "@Character Trophies/Adventure Mode Trophies/Luigi - Adventure Trophy",
    [0x158] = "@Character Trophies/Classic Mode Trophies/Luigi - Classic Trophy",
    [0x159] = "@Character Trophies/All-Star Mode Trophies/Luigi - All-Star Trophy",
    [0x15A] = "@Character Trophies/Adventure Mode Trophies/Jigglypuff - Adventure Trophy",
    [0x15B] = "@Character Trophies/Classic Mode Trophies/Jigglypuff - Classic Trophy",
    [0x15C] = "@Character Trophies/All-Star Mode Trophies/Jigglypuff - All-Star Trophy",
    [0x15D] = "@Character Trophies/Adventure Mode Trophies/Mewtwo - Adventure Trophy",
    [0x15E] = "@Character Trophies/Classic Mode Trophies/Mewtwo - Classic Trophy",
    [0x15F] = "@Character Trophies/All-Star Mode Trophies/Mewtwo - All-Star Trophy",
    [0x160] = "@Character Trophies/Adventure Mode Trophies/Marth - Adventure Trophy",
    [0x161] = "@Character Trophies/Classic Mode Trophies/Marth - Classic Trophy",
    [0x162] = "@Character Trophies/All-Star Mode Trophies/Marth - All-Star Trophy",
    [0x163] = "@Character Trophies/Adventure Mode Trophies/Mr. Game & Watch - Adventure Trophy",
    [0x164] = "@Character Trophies/Classic Mode Trophies/Mr. Game & Watch - Classic Trophy",
    [0x165] = "@Character Trophies/All-Star Mode Trophies/Mr. Game & Watch - All-Star Trophy",
    [0x166] = "@Character Trophies/Adventure Mode Trophies/Dr. Mario - Adventure Trophy",
    [0x167] = "@Character Trophies/Classic Mode Trophies/Dr. Mario - Classic Trophy",
    [0x168] = "@Character Trophies/All-Star Mode Trophies/Dr. Mario - All-Star Trophy",
    [0x169] = "@Character Trophies/Adventure Mode Trophies/Ganondorf - Adventure Trophy",
    [0x16A] = "@Character Trophies/Classic Mode Trophies/Ganondorf - Classic Trophy",
    [0x16B] = "@Character Trophies/All-Star Mode Trophies/Ganondorf - All-Star Trophy",
    [0x16C] = "@Character Trophies/Adventure Mode Trophies/Falco - Adventure Trophy",
    [0x16D] = "@Character Trophies/Classic Mode Trophies/Falco - Classic Trophy",
    [0x16E] = "@Character Trophies/All-Star Mode Trophies/Falco - All-Star Trophy",
    [0x16F] = "@Character Trophies/Adventure Mode Trophies/Young Link - Adventure Trophy",
    [0x170] = "@Character Trophies/Classic Mode Trophies/Young Link - Classic Trophy",
    [0x171] = "@Character Trophies/All-Star Mode Trophies/Young Link - All-Star Trophy",
    [0x172] = "@Character Trophies/Adventure Mode Trophies/Pichu - Adventure Trophy",
    [0x173] = "@Character Trophies/Classic Mode Trophies/Pichu - Classic Trophy",
    [0x174] = "@Character Trophies/All-Star Mode Trophies/Pichu - All-Star Trophy",
    [0x175] = "@Character Trophies/Adventure Mode Trophies/Roy - Adventure Trophy",
    [0x176] = "@Character Trophies/Classic Mode Trophies/Roy - Classic Trophy",
    [0x177] = "@Character Trophies/All-Star Mode Trophies/Roy - All-Star Trophy",

    -- =====================================
    -- SINGLE PLAYER MODE CHALLENGES
    -- =====================================
    [0x178] = "@Single Player Modes/Adventure Mode/Sub 18:20 Clear",
    [0x179] = "@Single Player Modes/Adventure Mode/Hard-Continueless Clear",
    [0x17A] = "@Single Player Modes/Adventure Mode/Escape Brinstar",
    [0x17B] = "@Single Player Modes/Adventure Mode/All Character Trophies",
    [0x17C] = "@Single Player Modes/Adventure Mode/Giga Bowser Continueless",
    [0x17D] = "@Single Player Modes/All-Star Mode/Clear",
    [0x17E] = "@Single Player Modes/All-Star Mode/Continueless Clear",
    [0x17F] = "@Single Player Modes/All-Star Mode/Hard Clear",
    [0x180] = "@Single Player Modes/All-Star Mode/All Character Trophies",
    [0x181] = "@Single Player Modes/Classic Mode/5 Minute Clear",
    [0x182] = "@Single Player Modes/Classic Mode/Hard-Continueless Clear",
    [0x183] = "@Single Player Modes/Classic Mode/All Character Trophies",
    [0x272] = "@Single Player Modes/Classic Mode/Game & Watch Clear",

    -- Multi-Man Melee
    [0x1A0] = "@Single Player Modes/Multi Man Melee/15 Minute Melee Clear",
    [0x1A1] = "@Single Player Modes/Multi Man Melee/100 Man Melee Sub 4 Minutes",
    [0x1A2] = "@Single Player Modes/Multi Man Melee/Cruel Melee 5 KO's",
    [0x1A3] = "@Single Player Modes/Multi Man Melee/Endless Melee 100 KO's",

    -- Training Mode
    [0x1AA] = "@Single Player Modes/Training Mode/125 Combined Combos",
    [0x1AB] = "@Single Player Modes/Training Mode/10-Hit Combo",
    [0x1AC] = "@Single Player Modes/Training Mode/20-Hit Combo",

    -- Home-Run Contest
    [0x1AD] = "@Single Player Modes/Home-Run Contest/16,404 Ft. Combined",
    [0x1AE] = "@Single Player Modes/Home-Run Contest/984 Ft.",
    [0x1AF] = "@Single Player Modes/Home-Run Contest/1,312 Ft.",
    [0x1B0] = "@Single Player Modes/Home-Run Contest/1,476 Ft.",

    -- =====================================
    -- TARGET TEST
    -- =====================================
    [0x184] = "@Target Test/Starting Characters/Mario",
    [0x185] = "@Target Test/Secret Characters/Dr. Mario",
    [0x186] = "@Target Test/Secret Characters/Luigi",
    [0x187] = "@Target Test/Secret Characters/Bowser",
    [0x188] = "@Target Test/Secret Characters/Peach",
    [0x189] = "@Target Test/Starting Characters/Yoshi",
    [0x18A] = "@Target Test/Starting Characters/Donkey Kong",
    [0x18B] = "@Target Test/Starting Characters/Captain Falcon",
    [0x18C] = "@Target Test/Secret Characters/Ganondorf",
    [0x18D] = "@Target Test/Secret Characters/Falco",
    [0x18E] = "@Target Test/Starting Characters/Fox",
    [0x18F] = "@Target Test/Starting Characters/Ness",
    [0x190] = "@Target Test/Secret Characters/Ice Climbers",
    [0x191] = "@Target Test/Starting Characters/Kirby",
    [0x192] = "@Target Test/Starting Characters/Samus",
    [0x193] = "@Target Test/Secret Characters/Zelda",
    [0x194] = "@Target Test/Starting Characters/Link",
    [0x195] = "@Target Test/Secret Characters/Young Link",
    [0x196] = "@Target Test/Secret Characters/Pichu",
    [0x197] = "@Target Test/Starting Characters/Pikachu",
    [0x198] = "@Target Test/Secret Characters/Jigglypuff",
    [0x199] = "@Target Test/Secret Characters/Mewtwo",
    [0x19A] = "@Target Test/Secret Characters/Mr. Game & Watch",
    [0x19B] = "@Target Test/Secret Characters/Marth",
    [0x19C] = "@Target Test/Secret Characters/Roy",

    -- Target Test Challenges
    [0x19D] = "@Target Test/Target Test Challenges/All Characters, Sub 12:30 Total Time",
    [0x19E] = "@Target Test/Target Test Challenges/All Characters",
    [0x19F] = "@Target Test/Target Test Challenges/All Characters, Sub 25 Minutes Total Time",

    -- =====================================
    -- CHARACTER UNLOCKS
    -- =====================================
    [0x1B9] = "@Character Unlocks/Secret Character Unlock Matches/Jigglypuff Unlock Match (Classic, Adventure, All-Star)",
    [0x1BA] = "@Character Unlocks/Secret Character Unlock Matches/Dr. Mario Unlock Match (Classic, Adventure, All-Star w\u{2215} Mario w\u{2215}o continues)",
    [0x1BB] = "@Character Unlocks/Secret Character Unlock Matches/Pichu Unlock Match (Event 37)",
    [0x1BC] = "@Character Unlocks/Secret Character Unlock Matches/Falco Unlock Match (100-Man Melee)",
    [0x1BD] = "@Character Unlocks/Secret Character Unlock Matches/Marth Unlock Match (Use starter characters)",
    [0x1BE] = "@Character Unlocks/Secret Character Unlock Matches/Young Link Unlock Match (Classic, Adventure, All-Star w\u{2215} 10 characters)",
    [0x1BF] = "@Character Unlocks/Secret Character Unlock Matches/Ganondorf Unlock Match (Event 29)",
    [0x1C0] = "@Character Unlocks/Secret Character Unlock Matches/Mewtwo Unlock Match (1 total hour of VS)",
    [0x1C1] = "@Character Unlocks/Secret Character Unlock Matches/Luigi Unlock Match (Adventure Stage 1 timer end 2 sec and defeat less 1 min)",
    [0x1C2] = "@Character Unlocks/Secret Character Unlock Matches/Roy Unlock Match (Classic, Adventure, All-Star w\u{2215} Marth w\u{2215}o continues)",
    [0x1C3] = "@Character Unlocks/Secret Character Unlock Matches/Game & Watch Unlock Match (Classic, Adventure, All-Star, Target Test w\u{2215} all other characters)",


    -- =====================================
    -- TROPHY COLLECTION
    -- =====================================
    -- Base Trophy Pool (Lottery Base)
    [0x1CC] = "@Trophy Collection/Lottery Base A to B/Andross (64)",
    [0x1CD] = "@Trophy Collection/Lottery Base A to B/Baby Bowser",
    [0x1CE] = "@Trophy Collection/Lottery Base A to B/Ball Kirby",
    [0x1CF] = "@Trophy Collection/Lottery Base A to B/Balloon Fighter",
    [0x1D0] = "@Trophy Collection/Lottery Base A to B/Barrel",
    [0x1D1] = "@Trophy Collection/Lottery Base A to B/Barrel Cannon",
    [0x1D2] = "@Trophy Collection/Lottery Base A to B/Bellossom",
    [0x1D3] = "@Trophy Collection/Lottery Base A to B/Birdo",
    [0x1D4] = "@Trophy Collection/Lottery Base A to B/Blastoise",
    [0x1D5] = "@Trophy Collection/Lottery Base A to B/Bob-omb",
    [0x1D6] = "@Trophy Collection/Lottery Base A to B/Bucket",
    [0x1D7] = "@Trophy Collection/Lottery Base A to B/Bulbasaur",
    [0x1D8] = "@Trophy Collection/Lottery Base C to E/Capsule",
    [0x1D9] = "@Trophy Collection/Lottery Base C to E/Chikorita",
    [0x1DA] = "@Trophy Collection/Lottery Base C to E/Clefairy",
    [0x1DB] = "@Trophy Collection/Lottery Base C to E/Coin",
    [0x1DC] = "@Trophy Collection/Lottery Base C to E/Crate",
    [0x1DD] = "@Trophy Collection/Lottery Base C to E/Crobat",
    [0x1DE] = "@Trophy Collection/Lottery Base C to E/Cyndaquil",
    [0x1DF] = "@Trophy Collection/Lottery Base C to E/Daisy",
    [0x1E0] = "@Trophy Collection/Lottery Base C to E/Donbe & Hikari",
    [0x1E1] = "@Trophy Collection/Lottery Base C to E/Dr. Stewart",
    [0x1E2] = "@Trophy Collection/Lottery Base C to E/Dr. Wright",
    [0x1E3] = "@Trophy Collection/Lottery Base C to E/Ducks",
    [0x1E4] = "@Trophy Collection/Lottery Base C to E/Egg",
    [0x1E5] = "@Trophy Collection/Lottery Base C to E/Excitebike",
    [0x1E6] = "@Trophy Collection/Lottery Base F to L/Fan",
    [0x1E7] = "@Trophy Collection/Lottery Base F to L/Fire Flower",
    [0x1E8] = "@Trophy Collection/Lottery Base F to L/Flipper",
    [0x1E9] = "@Trophy Collection/Lottery Base F to L/Goldeen",
    [0x1EA] = "@Trophy Collection/Lottery Base F to L/Heracross",
    [0x1EB] = "@Trophy Collection/Lottery Base F to L/Heririn",
    [0x1EC] = "@Trophy Collection/Lottery Base F to L/Home-Run Bat",
    [0x1ED] = "@Trophy Collection/Lottery Base F to L/Igglybuff",
    [0x1EE] = "@Trophy Collection/Lottery Base F to L/Jody Summer",
    [0x1EF] = "@Trophy Collection/Lottery Base F to L/Kirby Hat 1",
    [0x1F0] = "@Trophy Collection/Lottery Base F to L/Kirby Hat 2",
    [0x1F1] = "@Trophy Collection/Lottery Base F to L/Kirby Hat 3",
    [0x1F2] = "@Trophy Collection/Lottery Base F to L/Klap Trap",
    [0x1F3] = "@Trophy Collection/Lottery Base F to L/Koopa Troopa",
    [0x1F4] = "@Trophy Collection/Lottery Base F to L/Lakitu",
    [0x1F5] = "@Trophy Collection/Lottery Base M to R/Metal Mario",
    [0x1F6] = "@Trophy Collection/Lottery Base M to R/Metroid",
    [0x1F7] = "@Trophy Collection/Lottery Base M to R/Monster",
    [0x1F8] = "@Trophy Collection/Lottery Base M to R/Mr. Saturn",
    [0x1F9] = "@Trophy Collection/Lottery Base M to R/Party Ball",
    [0x1FA] = "@Trophy Collection/Lottery Base M to R/Poliwhirl",
    [0x1FB] = "@Trophy Collection/Lottery Base M to R/Porygon2",
    [0x1FC] = "@Trophy Collection/Lottery Base M to R/Racing Kart",
    [0x1FD] = "@Trophy Collection/Lottery Base M to R/Raphael Raven",
    [0x1FE] = "@Trophy Collection/Lottery Base M to R/Ray Gun",
    [0x1FF] = "@Trophy Collection/Lottery Base M to R/Rick",
    [0x200] = "@Trophy Collection/Lottery Base M to R/Ridley",
    [0x201] = "@Trophy Collection/Lottery Base M to R/Ryota Hayami",
    [0x202] = "@Trophy Collection/Lottery Base S to Z/Scizor",
    [0x203] = "@Trophy Collection/Lottery Base S to Z/Slippy Toad",
    [0x204] = "@Trophy Collection/Lottery Base S to Z/Snorlax",
    [0x205] = "@Trophy Collection/Lottery Base S to Z/Squirtle",
    [0x206] = "@Trophy Collection/Lottery Base S to Z/Starman",
    [0x207] = "@Trophy Collection/Lottery Base S to Z/Starman (EarthBound)",
    [0x208] = "@Trophy Collection/Lottery Base S to Z/Star Rod",
    [0x209] = "@Trophy Collection/Lottery Base S to Z/Steelix",
    [0x20A] = "@Trophy Collection/Lottery Base S to Z/Super Mushroom",
    [0x20B] = "@Trophy Collection/Lottery Base S to Z/Super Scope",
    [0x20C] = "@Trophy Collection/Lottery Base S to Z/Thwomp",
    [0x20D] = "@Trophy Collection/Lottery Base S to Z/Toad",
    [0x20E] = "@Trophy Collection/Lottery Base S to Z/Topi",
    [0x20F] = "@Trophy Collection/Lottery Base S to Z/Totodile",
    [0x210] = "@Trophy Collection/Lottery Base S to Z/Waddle Dee",
    [0x211] = "@Trophy Collection/Lottery Base S to Z/Weezing",
    [0x212] = "@Trophy Collection/Lottery Base S to Z/Wobbuffet",
    [0x213] = "@Trophy Collection/Lottery Base S to Z/ZERO-ONE",

    -- Single Player Trophy Unlocks
    [0x214] = "@Trophy Collection/Any Main 1-P (No All-Star) A to O/Ayumi Tachibana",
    [0x215] = "@Trophy Collection/Any Main 1-P (No All-Star) A to O/Banzai Bill",
    [0x216] = "@Trophy Collection/Any Main 1-P (No All-Star) A to O/Beam Sword",
    [0x217] = "@Trophy Collection/Any Main 1-P (No All-Star) A to O/Charizard",
    [0x218] = "@Trophy Collection/Any Main 1-P (No All-Star) A to O/Cleffa",
    [0x219] = "@Trophy Collection/Any Main 1-P (No All-Star) A to O/Electrode",
    [0x21A] = "@Trophy Collection/Any Main 1-P (No All-Star) A to O/Fire Kirby",
    [0x21B] = "@Trophy Collection/Any Main 1-P (No All-Star) A to O/Four Giants",
    [0x21C] = "@Trophy Collection/Any Main 1-P (No All-Star) A to O/Freezie",
    [0x21D] = "@Trophy Collection/Any Main 1-P (No All-Star) A to O/Goron",
    [0x21E] = "@Trophy Collection/Any Main 1-P (No All-Star) A to O/Green Shell",
    [0x21F] = "@Trophy Collection/Any Main 1-P (No All-Star) A to O/Koopa Paratroopa",
    [0x220] = "@Trophy Collection/Any Main 1-P (No All-Star) A to O/Like Like",
    [0x221] = "@Trophy Collection/Any Main 1-P (No All-Star) A to O/Love Giant",
    [0x222] = "@Trophy Collection/Any Main 1-P (No All-Star) A to O/Marill",
    [0x223] = "@Trophy Collection/Any Main 1-P (No All-Star) A to O/Master Sword",
    [0x224] = "@Trophy Collection/Any Main 1-P (No All-Star) A to O/Octorok",
    [0x225] = "@Trophy Collection/Any Main 1-P (No All-Star) P to Z/Parasol",
    [0x226] = "@Trophy Collection/Any Main 1-P (No All-Star) P to Z/Paula",
    [0x227] = "@Trophy Collection/Any Main 1-P (No All-Star) P to Z/Pit",
    [0x228] = "@Trophy Collection/Any Main 1-P (No All-Star) P to Z/Plum",
    [0x229] = "@Trophy Collection/Any Main 1-P (No All-Star) P to Z/ReDead",
    [0x22A] = "@Trophy Collection/Any Main 1-P (No All-Star) P to Z/Screw Attack",
    [0x22B] = "@Trophy Collection/Any Main 1-P (No All-Star) P to Z/Staryu",
    [0x22C] = "@Trophy Collection/Any Main 1-P (No All-Star) P to Z/Vegetable",
    [0x22D] = "@Trophy Collection/Any Main 1-P (No All-Star) P to Z/Viruses",
    [0x22E] = "@Trophy Collection/Any Main 1-P (No All-Star) P to Z/Warp Star",

    -- Additional Lottery Base Trophies
    [0x22F] = "@Trophy Collection/Lottery Base A to B/Bubbles",
    [0x230] = "@Trophy Collection/Lottery Base C to E/Chansey",
    [0x231] = "@Trophy Collection/Lottery Base C to E/Dixie Kong",
    [0x232] = "@Trophy Collection/Lottery Base C to E/Eevee",
    [0x233] = "@Trophy Collection/Lottery Base C to E/Eggplant Man",
    [0x234] = "@Trophy Collection/Lottery Base F to L/Fighter Kirby",
    [0x235] = "@Trophy Collection/Lottery Base F to L/Jeff",
    [0x236] = "@Trophy Collection/Lottery Base M to R/Maruo Maruhige",
    [0x237] = "@Trophy Collection/Lottery Base M to R/Misty",
    [0x238] = "@Trophy Collection/Lottery Base M to R/Professor Oak",
    [0x239] = "@Trophy Collection/Lottery Base M to R/Ray Mk II",
    [0x23A] = "@Trophy Collection/Lottery Base M to R/Red Shell",

    -- Lottery Adventure-Classic Clear Trophies
    [0x23B] = "@Trophy Collection/Lottery Adventure-Classic Clear A to S/Arwing",
    [0x23C] = "@Trophy Collection/Lottery Adventure-Classic Clear A to S/Baby Mario",
    [0x23D] = "@Trophy Collection/Lottery Adventure-Classic Clear A to S/Bayonette",
    [0x23E] = "@Trophy Collection/Lottery Adventure-Classic Clear A to S/Chozo Statue",
    [0x23F] = "@Trophy Collection/Lottery Adventure-Classic Clear A to S/Ditto",
    [0x240] = "@Trophy Collection/Lottery Adventure-Classic Clear A to S/Fountain of Dreams",
    [0x241] = "@Trophy Collection/Lottery Adventure-Classic Clear A to S/Gooey",
    [0x242] = "@Trophy Collection/Lottery Adventure-Classic Clear A to S/Great Fox",
    [0x243] = "@Trophy Collection/Lottery Adventure-Classic Clear A to S/Hammer",
    [0x244] = "@Trophy Collection/Lottery Adventure-Classic Clear A to S/King Dedede",
    [0x245] = "@Trophy Collection/Lottery Adventure-Classic Clear A to S/Moon",
    [0x246] = "@Trophy Collection/Lottery Adventure-Classic Clear A to S/Pak E. Derm",
    [0x247] = "@Trophy Collection/Lottery Adventure-Classic Clear A to S/Pidgit",
    [0x248] = "@Trophy Collection/Lottery Adventure-Classic Clear A to S/Pikmin",
    [0x249] = "@Trophy Collection/Lottery Adventure-Classic Clear A to S/Poké Ball",
    [0x24A] = "@Trophy Collection/Lottery Adventure-Classic Clear A to S/Pokémon Stadium",
    [0x24B] = "@Trophy Collection/Lottery Adventure-Classic Clear A to S/Princess Peach's Castle",
    [0x24C] = "@Trophy Collection/Lottery Adventure-Classic Clear A to S/Shy Guys",
    [0x24D] = "@Trophy Collection/Lottery Adventure-Classic Clear A to S/Suicune",
    [0x24E] = "@Trophy Collection/Lottery Adventure-Classic Clear T to Z/Tingle",
    [0x24F] = "@Trophy Collection/Lottery Adventure-Classic Clear T to Z/Turtle",
    [0x250] = "@Trophy Collection/Lottery Adventure-Classic Clear T to Z/Venusaur",
    [0x251] = "@Trophy Collection/Lottery Adventure-Classic Clear T to Z/Whispy Woods",

    -- Lottery Secret Characters Trophies
    [0x252] = "@Trophy Collection/Lottery Secret Characters/Alpha",
    [0x253] = "@Trophy Collection/Lottery Secret Characters/Articuno",
    [0x254] = "@Trophy Collection/Lottery Secret Characters/Boo",
    [0x255] = "@Trophy Collection/Lottery Secret Characters/Hate Giant",
    [0x256] = "@Trophy Collection/Lottery Secret Characters/Ho-Oh",
    [0x257] = "@Trophy Collection/Lottery Secret Characters/King K. Rool",
    [0x258] = "@Trophy Collection/Lottery Secret Characters/Moltres",
    [0x259] = "@Trophy Collection/Lottery Secret Characters/Ocarina of Time",
    [0x25A] = "@Trophy Collection/Lottery Secret Characters/Raikou",
    [0x25B] = "@Trophy Collection/Lottery Secret Characters/Zapdos",

    -- Lottery 250 Trophies
    [0x25C] = "@Trophy Collection/Lottery 250 Trophies/GCN",
    [0x25D] = "@Trophy Collection/Lottery 250 Trophies/Koopa Clown Car",
    [0x25E] = "@Trophy Collection/Lottery 250 Trophies/Raccoon Mario",
    [0x25F] = "@Trophy Collection/Lottery 250 Trophies/Waluigi",

    -- Lottery 200 Vs. Matches Trophies
    [0x262] = "@Trophy Collection/Lottery 200 Vs. Matches/Andross",
    [0x263] = "@Trophy Collection/Lottery 200 Vs. Matches/Annie",
    [0x264] = "@Trophy Collection/Lottery 200 Vs. Matches/Cloaking Device",
    [0x265] = "@Trophy Collection/Lottery 200 Vs. Matches/Kensuke Kimachi",
    [0x266] = "@Trophy Collection/Lottery 200 Vs. Matches/Lugia",
    [0x267] = "@Trophy Collection/Lottery 200 Vs. Matches/Megavitamins",
    [0x268] = "@Trophy Collection/Lottery 200 Vs. Matches/Meta-Knight",
    [0x269] = "@Trophy Collection/Lottery 200 Vs. Matches/Peppy Hare",
    [0x26A] = "@Trophy Collection/Lottery 200 Vs. Matches/Poison Mushroom",
    [0x26B] = "@Trophy Collection/Lottery 200 Vs. Matches/Polar Bear",
    [0x26C] = "@Trophy Collection/Lottery 200 Vs. Matches/Poo",
    [0x26D] = "@Trophy Collection/Lottery 200 Vs. Matches/Samurai Goroh",
    [0x26E] = "@Trophy Collection/Lottery 200 Vs. Matches/Stanley",
    [0x26F] = "@Trophy Collection/Lottery 200 Vs. Matches/Togepi",
    [0x270] = "@Trophy Collection/Lottery 200 Vs. Matches/Totakeke",
    [0x271] = "@Trophy Collection/Lottery 200 Vs. Matches/Vacuum Luigi",

    -- =====================================
    -- BONUS ACHIEVEMENTS
    -- =====================================
    -- Combat Bonuses
    [0x01] = "@Bonus Achievements/Combat Bonuses 1/Dedicated Specialist",
    [0x02] = "@Bonus Achievements/Combat Bonuses 1/One-Two Punch",
    [0x03] = "@Bonus Achievements/Combat Bonuses 1/First Strike",
    [0x04] = "@Bonus Achievements/Combat Bonuses 1/150% Damage",
    [0x05] = "@Bonus Achievements/Combat Bonuses 1/200% Damage",
    [0x06] = "@Bonus Achievements/Combat Bonuses 1/250% Damage",
    [0x07] = "@Bonus Achievements/Combat Bonuses 1/300% Damage",
    [0x08] = "@Bonus Achievements/Combat Bonuses 1/350% Damage",
    [0x0C] = "@Bonus Achievements/Combat Bonuses 1/Berserker",
    [0x0D] = "@Bonus Achievements/Combat Bonuses 1/Smash King",
    [0x0E] = "@Bonus Achievements/Combat Bonuses 1/Smash Maniac",
    [0x0F] = "@Bonus Achievements/Combat Bonuses 1/Smash-less",
    [0x10] = "@Bonus Achievements/Combat Bonuses 1/Specialist",
    [0x12] = "@Bonus Achievements/Combat Bonuses 1/Full Power",
    [0x38] = "@Bonus Achievements/Combat Bonuses 1/Heavy Damage",
    [0x39] = "@Bonus Achievements/Combat Bonuses 1/Sniper",
    [0x3A] = "@Bonus Achievements/Combat Bonuses 1/Brawler",
    [0x3B] = "@Bonus Achievements/Combat Bonuses 1/Precise Aim",
    [0x33] = "@Bonus Achievements/Combat Bonuses 1/Pummeler",
    [0x34] = "@Bonus Achievements/Combat Bonuses 1/Fists of Fury",
    [0x35] = "@Bonus Achievements/Combat Bonuses 2/Close Call",
    [0x36] = "@Bonus Achievements/Combat Bonuses 2/Opportunist",
    [0x37] = "@Bonus Achievements/Combat Bonuses 2/Spectator",
    [0xBF] = "@Bonus Achievements/Combat Bonuses 2/KO Artist",
    [0xC0] = "@Bonus Achievements/Combat Bonuses 2/KO Master",
    [0xC1] = "@Bonus Achievements/Combat Bonuses 2/Offensive Artist",
    [0xC2] = "@Bonus Achievements/Combat Bonuses 2/Offensive Master",
    [0x3F] = "@Bonus Achievements/Combat Bonuses 2/Cuddly Bear",
    [0x40] = "@Bonus Achievements/Combat Bonuses 2/Punching Bag",
    [0x41] = "@Bonus Achievements/Combat Bonuses 2/Stale Moves",
    [0x42] = "@Bonus Achievements/Combat Bonuses 2/Blind Eye",
    [0x43] = "@Bonus Achievements/Combat Bonuses 2/Crowd Favorite",
    [0x44] = "@Bonus Achievements/Combat Bonuses 2/Master of Suspense",
    [0x45] = "@Bonus Achievements/Combat Bonuses 2/Lost in Space",
    [0x46] = "@Bonus Achievements/Combat Bonuses 2/Lost Luggage",
    [0x6E] = "@Bonus Achievements/Combat Bonuses 2/Bully",
    [0x6F] = "@Bonus Achievements/Combat Bonuses 2/Coward",
    [0x70] = "@Bonus Achievements/Combat Bonuses 2/In the Fray",
    [0x71] = "@Bonus Achievements/Combat Bonuses 2/Friendly Foe",
    [0x72] = "@Bonus Achievements/Combat Bonuses 2/Center Stage",
    [0x76] = "@Bonus Achievements/Combat Bonuses 3/Pacifist",
    [0x77] = "@Bonus Achievements/Combat Bonuses 3/Moment of Silence",
    [0x78] = "@Bonus Achievements/Combat Bonuses 3/Impervious",
    [0x79] = "@Bonus Achievements/Combat Bonuses 3/Immortal",
    [0x7A] = "@Bonus Achievements/Combat Bonuses 3/Switzerland",
    [0x7B] = "@Bonus Achievements/Combat Bonuses 3/Predator",
    [0x7C] = "@Bonus Achievements/Combat Bonuses 3/Solar Being",
    [0x7D] = "@Bonus Achievements/Combat Bonuses 3/Stalker",

    -- Movement and Positioning Bonuses
    [0x09] = "@Bonus Achievements/Movement and Positioning Bonuses 1/All Variations",
    [0x0A] = "@Bonus Achievements/Movement and Positioning Bonuses 1/All on One",
    [0x0B] = "@Bonus Achievements/Movement and Positioning Bonuses 1/Lethal Weapon",
    [0x11] = "@Bonus Achievements/Movement and Positioning Bonuses 1/Meteor Master",
    [0x13] = "@Bonus Achievements/Movement and Positioning Bonuses 1/Meteor Survivor",
    [0x14] = "@Bonus Achievements/Movement and Positioning Bonuses 1/Flying Meteor",
    [0x15] = "@Bonus Achievements/Movement and Positioning Bonuses 1/Exceptional Aim",
    [0x16] = "@Bonus Achievements/Movement and Positioning Bonuses 1/Perfect Aim",
    [0x17] = "@Bonus Achievements/Movement and Positioning Bonuses 1/All Ground",
    [0x18] = "@Bonus Achievements/Movement and Positioning Bonuses 1/All Aerial",
    [0x19] = "@Bonus Achievements/Movement and Positioning Bonuses 1/Bird of Prey",
    [0x1A] = "@Bonus Achievements/Movement and Positioning Bonuses 1/Combo King",
    [0x1B] = "@Bonus Achievements/Movement and Positioning Bonuses 1/Juggler",
    [0x1C] = "@Bonus Achievements/Movement and Positioning Bonuses 1/Backstabber",
    [0x1D] = "@Bonus Achievements/Movement and Positioning Bonuses 1/Sweeper",
    [0x1E] = "@Bonus Achievements/Movement and Positioning Bonuses 1/Clean Sweep",
    [0x1F] = "@Bonus Achievements/Movement and Positioning Bonuses 1/Meteor Smash",
    [0x20] = "@Bonus Achievements/Movement and Positioning Bonuses 1/Meteor Clear",
    [0x21] = "@Bonus Achievements/Movement and Positioning Bonuses 1/Aerialist",
    [0x22] = "@Bonus Achievements/Movement and Positioning Bonuses 2/Acrobat",
    [0x23] = "@Bonus Achievements/Movement and Positioning Bonuses 2/Cement Shoes",
    [0x24] = "@Bonus Achievements/Movement and Positioning Bonuses 2/Head Banger",
    [0x25] = "@Bonus Achievements/Movement and Positioning Bonuses 2/Elbow Room",
    [0x26] = "@Bonus Achievements/Movement and Positioning Bonuses 3/Power Shielder",
    [0x27] = "@Bonus Achievements/Movement and Positioning Bonuses 3/Shield Buster",
    [0x30] = "@Bonus Achievements/Movement and Positioning Bonuses 2/Eagle",
    [0x31] = "@Bonus Achievements/Movement and Positioning Bonuses 2/Compass Tosser",
    [0x32] = "@Bonus Achievements/Movement and Positioning Bonuses 2/Throw Down",
    [0x2B] = "@Bonus Achievements/Movement and Positioning Bonuses 2/Stiff Knees",
    [0x2C] = "@Bonus Achievements/Movement and Positioning Bonuses 2/Run, Don't Walk",
    [0x2D] = "@Bonus Achievements/Movement and Positioning Bonuses 2/Ambler",
    [0x2E] = "@Bonus Achievements/Movement and Positioning Bonuses 2/No Hurry",
    [0x2F] = "@Bonus Achievements/Movement and Positioning Bonuses 2/Marathon Man",
    [0x48] = "@Bonus Achievements/Movement and Positioning Bonuses 2/Rock Steady",
    [0x49] = "@Bonus Achievements/Movement and Positioning Bonuses 2/Pratfaller",
    [0x4A] = "@Bonus Achievements/Movement and Positioning Bonuses 2/Face Planter",
    [0x4B] = "@Bonus Achievements/Movement and Positioning Bonuses 2/Twinkle Toes",
    [0x4C] = "@Bonus Achievements/Movement and Positioning Bonuses 2/Floor Diver",
    [0x4D] = "@Bonus Achievements/Movement and Positioning Bonuses 2/No R 4 U",
    [0x4E] = "@Bonus Achievements/Movement and Positioning Bonuses 1/Climactic Clash",
    [0x4F] = "@Bonus Achievements/Movement and Positioning Bonuses 2/Floored",
    [0x50] = "@Bonus Achievements/Movement and Positioning Bonuses 2/Life on the Edge",
    [0x51] = "@Bonus Achievements/Movement and Positioning Bonuses 3Poser",
    [0x52] = "@Bonus Achievements/Movement and Positioning Bonuses 3/Poser Poseur",
    [0x53] = "@Bonus Achievements/Movement and Positioning Bonuses 3/Poser Power",
    [0x54] = "@Bonus Achievements/Movement and Positioning Bonuses 3/Pose Breaker",
    [0x55] = "@Bonus Achievements/Movement and Positioning Bonuses 3/Instant Poser",
    [0x56] = "@Bonus Achievements/Movement and Positioning Bonuses 3/Button Masher",
    [0x57] = "@Bonus Achievements/Movement and Positioning Bonuses 3/Button Holder",
    [0x58] = "@Bonus Achievements/Movement and Positioning Bonuses 3/Shield Stupidity",
    [0x59] = "@Bonus Achievements/Movement and Positioning Bonuses 3/Shield Saver",
    [0x5A] = "@Bonus Achievements/Movement and Positioning Bonuses 3/Skid Master",
    [0x5B] = "@Bonus Achievements/Movement and Positioning Bonuses 3/Rock Climber",
    [0x5C] = "@Bonus Achievements/Movement and Positioning Bonuses 3/Edge Hog",
    [0x5D] = "@Bonus Achievements/Movement and Positioning Bonuses 3/Cliffhanger",
    [0x28] = "@Bonus Achievements/Movement and Positioning Bonuses 3/Shattered Shield",
    [0x29] = "@Bonus Achievements/Movement and Positioning Bonuses 3/Statue",
    [0x2A] = "@Bonus Achievements/Movement and Positioning Bonuses 3/Never Look Back",
    [0xDA] = "@Bonus Achievements/Movement and Positioning Bonuses 3/Control Freak",

    -- KO Type Bonuses
    [0x5E] = "@Bonus Achievements/KO Type Bonuses 1/Sacrificial KO",
    [0x5F] = "@Bonus Achievements/KO Type Bonuses 1/Avenger KO",
    [0x60] = "@Bonus Achievements/KO Type Bonuses 1/Double KO",
    [0x61] = "@Bonus Achievements/KO Type Bonuses 1/Triple KO",
    [0x62] = "@Bonus Achievements/KO Type Bonuses 1/Quadruple KO",
    [0x63] = "@Bonus Achievements/KO Type Bonuses 1/Quintuple KO",
    [0x64] = "@Bonus Achievements/KO Type Bonuses 1/Dead-Weight KO",
    [0x65] = "@Bonus Achievements/KO Type Bonuses 1/Kiss-the-Floor KO",
    [0x66] = "@Bonus Achievements/KO Type Bonuses 1/Poser KO",
    [0x67] = "@Bonus Achievements/KO Type Bonuses 1/Cheap KO",
    [0x68] = "@Bonus Achievements/KO Type Bonuses 1/Bank-Shot KO",
    [0x69] = "@Bonus Achievements/KO Type Bonuses 1/Timely KO",
    [0x6A] = "@Bonus Achievements/KO Type Bonuses 1/Special KO",
    [0x6B] = "@Bonus Achievements/KO Type Bonuses 1/Hangman's KO",
    [0x6C] = "@Bonus Achievements/KO Type Bonuses 1/KO 64",
    [0x6D] = "@Bonus Achievements/KO Type Bonuses 1/Bubble-Blast KO",
    [0x73] = "@Bonus Achievements/KO Type Bonuses 1/Star KO",
    [0x74] = "@Bonus Achievements/KO Type Bonuses 1/Wimpy KO",
    [0x75] = "@Bonus Achievements/KO Type Bonuses 1/Bull's-eye KO",
    [0x7E] = "@Bonus Achievements/KO Type Bonuses 1/Carrier KO",
    [0x95] = "@Bonus Achievements/KO Type Bonuses 2/Assisted KO",
    [0xDE] = "@Bonus Achievements/KO Type Bonuses 2/Rocket KO",
    [0x9D] = "@Bonus Achievements/KO Type Bonuses 2/Tiny KO",
    [0x9E] = "@Bonus Achievements/KO Type Bonuses 2/Invisible KO",
    [0xAB] = "@Bonus Achievements/KO Type Bonuses 2/Giant KO",
    [0xA4] = "@Bonus Achievements/KO Type Bonuses 2/Metal KO",
    [0xA5] = "@Bonus Achievements/KO Type Bonuses 2/Freezie KO",
    [0xA6] = "@Bonus Achievements/KO Type Bonuses 2/Flipper KO",
    [0xA3] = "@Bonus Achievements/KO Type Bonuses 2/Invincible KO",
    [0x8C] = "@Bonus Achievements/KO Type Bonuses 2/Capsule KO",
    [0xB0] = "@Bonus Achievements/KO Type Bonuses 2/Screw-Attack KO",
    [0xB1] = "@Bonus Achievements/KO Type Bonuses 2/Warp-Star KO",
    [0x9F] = "@Bonus Achievements/KO Type Bonuses 2/Bunny-hood Blast",
    [0xC4] = "@Bonus Achievements/KO Type Bonuses 2/Paratroopa KO",
    [0xC5] = "@Bonus Achievements/KO Type Bonuses 2/ReDead KO",
    [0xC6] = "@Bonus Achievements/KO Type Bonuses 2/Like Like KO",
    [0xC7] = "@Bonus Achievements/KO Type Bonuses 2/Octorok KO",
    [0xC8] = "@Bonus Achievements/KO Type Bonuses 2/Topi KO",
    [0xC9] = "@Bonus Achievements/KO Type Bonuses 2/Polar Bear KO",
    [0xCA] = "@Bonus Achievements/KO Type Bonuses 2/Shy Guy KO",
    [0xCD] = "@Bonus Achievements/KO Type Bonuses 3/Pokémon KO",
    [0xD0] = "@Bonus Achievements/KO Type Bonuses 3/Goomba KO",
    [0xD1] = "@Bonus Achievements/KO Type Bonuses 3/Koopa KO",

    -- Item-Related Bonuses
    [0x3C] = "@Bonus Achievements/Item-Related Bonuses 1/Pitcher",
    [0x3D] = "@Bonus Achievements/Item-Related Bonuses 1/Butterfingers",
    [0x3E] = "@Bonus Achievements/Item-Related Bonuses 1/All Thumbs",
    [0x7F] = "@Bonus Achievements/Item-Related Bonuses 1/Weight Lifter",
    [0x80] = "@Bonus Achievements/Item-Related Bonuses 1/Item Catcher",
    [0x81] = "@Bonus Achievements/Item-Related Bonuses 1/Reciprocator",
    [0x82] = "@Bonus Achievements/Item-Related Bonuses 1/Item Self-Destruct",
    [0x84] = "@Bonus Achievements/Item-Related Bonuses 1/Item Hog",
    [0x85] = "@Bonus Achievements/Item-Related Bonuses 1/Item Collector",
    [0x88] = "@Bonus Achievements/Item-Related Bonuses 1/Item-less",
    [0x89] = "@Bonus Achievements/Item-Related Bonuses 1/Item Specialist",
    [0x83] = "@Bonus Achievements/Item-Related Bonuses 1/Triple Items",
    [0x86] = "@Bonus Achievements/Item-Related Bonuses 1/Lucky Threes",
    [0x87] = "@Bonus Achievements/Item-Related Bonuses 1/Jackpot",
    [0x8A] = "@Bonus Achievements/Item-Related Bonuses 1/Item Chucker",
    [0x8B] = "@Bonus Achievements/Item-Related Bonuses 1/Item Smasher",
    [0xA7] = "@Bonus Achievements/Item-Related Bonuses 2/Mr. Saturn Fan",
    [0xA8] = "@Bonus Achievements/Item-Related Bonuses 2/Mrs. Saturn",
    [0xA9] = "@Bonus Achievements/Item-Related Bonuses 2/Saturn Siblings",
    [0xAA] = "@Bonus Achievements/Item-Related Bonuses 2/Saturn Ringer",
    [0xCC] = "@Bonus Achievements/Item-Related Bonuses 2/Bob-omb Squad",
    [0xCE] = "@Bonus Achievements/Item-Related Bonuses 2/Mew Catcher",
    [0xCF] = "@Bonus Achievements/Item-Related Bonuses 2/Celebi Catcher",
    [0xD2] = "@Bonus Achievements/Item-Related Bonuses 1/Beam Swordsman",
    [0xD3] = "@Bonus Achievements/Item-Related Bonuses 1/Home-Run King",
    [0xD4] = "@Bonus Achievements/Item-Related Bonuses 1/Laser Marksman",
    [0xD5] = "@Bonus Achievements/Item-Related Bonuses 1/Flame Thrower",
    [0xD6] = "@Bonus Achievements/Item-Related Bonuses 2/Hammer Throw",
    [0xD7] = "@Bonus Achievements/Item-Related Bonuses 2/Headless Hammer",
    [0xD8] = "@Bonus Achievements/Item-Related Bonuses 2/Super Spy",
    [0xD9] = "@Bonus Achievements/Item-Related Bonuses 2/Bob-omb's Away",
    [0xDF] = "@Bonus Achievements/Item-Related Bonuses 2/Minimalist",
    [0xE0] = "@Bonus Achievements/Item-Related Bonuses 2/Materialist",

    -- Mode-Specific Bonuses
    [0xEE] = "@Bonus Achievements/Mode-Specific Bonuses 1/Classic Clear",
    [0xEF] = "@Bonus Achievements/Mode-Specific Bonuses 1/Adventure Clear",
    [0xF0] = "@Bonus Achievements/Mode-Specific Bonuses 1/All-Star Clear",
    [0xE9] = "@Bonus Achievements/Mode-Specific Bonuses 1/Giga Bowser KO",
    [0xE4] = "@Bonus Achievements/Mode-Specific Bonuses 1/Crazy Hand KO",
    [0xE5] = "@Bonus Achievements/Mode-Specific Bonuses 1/Luigi KO",
    [0xE7] = "@Bonus Achievements/Mode-Specific Bonuses 1/Giant Kirby KO",
    [0xE8] = "@Bonus Achievements/Mode-Specific Bonuses 1/Metal Bros. KO",
    [0xE1] = "@Bonus Achievements/Mode-Specific Bonuses 1/Collector",
    [0xE2] = "@Bonus Achievements/Mode-Specific Bonuses 1/Target Master",
    [0xE3] = "@Bonus Achievements/Mode-Specific Bonuses 1/Hobbyist",
    [0xE6] = "@Bonus Achievements/Mode-Specific Bonuses 1/Link Master",
    [0xEA] = "@Bonus Achievements/Mode-Specific Bonuses 1/Continuation",
    [0xEB] = "@Bonus Achievements/Mode-Specific Bonuses 1/Speedster",
    [0xEC] = "@Bonus Achievements/Mode-Specific Bonuses 1/Speed Demon",
    [0xED] = "@Bonus Achievements/Mode-Specific Bonuses 1/Melee Master",
    [0xF1] = "@Bonus Achievements/Mode-Specific Bonuses 1/Very Hard Clear",
    [0xF5] = "@Bonus Achievements/Mode-Specific Bonuses 1/No-Damage Clear",
    [0xF6] = "@Bonus Achievements/Mode-Specific Bonuses 1/No-Miss Clear",
    [0x47] = "@Bonus Achievements/Mode-Specific Bonuses 1/Half-Minute Man",
    [0x93] = "@Bonus Achievements/Mode-Specific Bonuses 2/Lucky Number Seven",
    [0x94] = "@Bonus Achievements/Mode-Specific Bonuses 2/Last Second",
    [0x8D] = "@Bonus Achievements/Mode-Specific Bonuses 2/Environmental Hazard",
    [0x8E] = "@Bonus Achievements/Mode-Specific Bonuses 2/Angelic",
    [0x8F] = "@Bonus Achievements/Mode-Specific Bonuses 2/Magnified Finish",
    [0x90] = "@Bonus Achievements/Mode-Specific Bonuses 2/Fighter Stance",
    [0x91] = "@Bonus Achievements/Mode-Specific Bonuses 2/Mystic",
    [0x92] = "@Bonus Achievements/Mode-Specific Bonuses 2/Shooting Star",
    [0x96] = "@Bonus Achievements/Mode-Specific Bonuses 2/Foresight",
    [0x97] = "@Bonus Achievements/Mode-Specific Bonuses 2/First to Fall",
    [0x98] = "@Bonus Achievements/Mode-Specific Bonuses 2/Cliff Diver",
    [0x99] = "@Bonus Achievements/Mode-Specific Bonuses 2/Quitter",
    [0x9A] = "@Bonus Achievements/Mode-Specific Bonuses 2/Shameful Fall",
    [0x9B] = "@Bonus Achievements/Mode-Specific Bonuses 2/World Traveler",
    [0x9C] = "@Bonus Achievements/Mode-Specific Bonuses 2/Ground Pounded",
    [0xA0] = "@Bonus Achievements/Mode-Specific Bonuses 2/Vegetarian",
    [0xA1] = "@Bonus Achievements/Mode-Specific Bonuses 2/Heartthrob",
    [0xA2] = "@Bonus Achievements/Mode-Specific Bonuses 2/Invincible Finish",
    [0xAC] = "@Bonus Achievements/Mode-Specific Bonuses 2/Gardener Finish",
    [0xAD] = "@Bonus Achievements/Mode-Specific Bonuses 2/Flower Finish",
    [0xAE] = "@Bonus Achievements/Mode-Specific Bonuses 3/Super Scoper",
    [0xAF] = "@Bonus Achievements/Mode-Specific Bonuses 3/Screwed Up",
    [0xB2] = "@Bonus Achievements/Mode-Specific Bonuses 3/Mycologist",
    [0xB3] = "@Bonus Achievements/Mode-Specific Bonuses 3/Mario Maniac",
    [0xB4] = "@Bonus Achievements/Mode-Specific Bonuses 3/Connoisseur",
    [0xB5] = "@Bonus Achievements/Mode-Specific Bonuses 3/Gourmet",
    [0xB6] = "@Bonus Achievements/Mode-Specific Bonuses 3/Battering Ram",
    [0xB7] = "@Bonus Achievements/Mode-Specific Bonuses 3/Straight Shooter",
    [0xB8] = "@Bonus Achievements/Mode-Specific Bonuses 3/Wimp",
    [0xB9] = "@Bonus Achievements/Mode-Specific Bonuses 3/Shape-Shifter",
    [0xBA] = "@Bonus Achievements/Mode-Specific Bonuses 3/Chuck Wagon",
    [0xBB] = "@Bonus Achievements/Mode-Specific Bonuses 3/Parasol Finish",
    [0xBC] = "@Bonus Achievements/Mode-Specific Bonuses 3/Last Place",
    [0xBD] = "@Bonus Achievements/Mode-Specific Bonuses 3/Wire to Wire",
    [0xBE] = "@Bonus Achievements/Mode-Specific Bonuses 3/Whipping Boy",
    [0xC3] = "@Bonus Achievements/Mode-Specific Bonuses 3/Frequent Faller",
    [0xCB] = "@Bonus Achievements/Mode-Specific Bonuses 3/First Place",
    [0xDB] = "@Bonus Achievements/Mode-Specific Bonuses 3/Peaceful Warrior",
    [0xDC] = "@Bonus Achievements/Mode-Specific Bonuses 3/Down, But Not Out",
    [0xDD] = "@Bonus Achievements/Mode-Specific Bonuses 3/Merciful Master",
    [0xF2] = "@Bonus Achievements/Mode-Specific Bonuses 4/Fall Guy",
    [0xF3] = "@Bonus Achievements/Mode-Specific Bonuses 4/Self-Destructor",
    [0xF4] = "@Bonus Achievements/Mode-Specific Bonuses 4/Master of Disaster",

    -- =====================================
    -- GENERAL ACHIEVEMENTS
    -- =====================================
    [0x1A5] = "@General Game Achievements/Gameplay Milestones/100 Coins",
    [0x1A6] = "@General Game Achievements/Gameplay Milestones/10 KO's",
    [0x260] = "@General Game Achievements/Gameplay Milestones/50 KO's",
    [0x1A7] = "@General Game Achievements/Gameplay Milestones/Walk 100 Meters",
    [0x1A8] = "@General Game Achievements/Gameplay Milestones/See Mew",
    [0x1A9] = "@General Game Achievements/Gameplay Milestones/See Celebi",

    -- Game Completion Goals
    [0x1A4] = "@General Game Achievements/General Game Goals/All Bonuses",
    [0x1B1] = "@General Game Achievements/General Game Goals/All Stages + Secret Characters",
    [0x1B2] = "@General Game Achievements/General Game Goals/Unlock Luigi, Jigglypuff, Mewtwo, Mr. Game & Watch, and Marth",
    [0x1B3] = "@General Game Achievements/General Game Goals/Unlock Roy, Pichu, Ganondorf, Dr. Mario, Young Link, and Falco",
    [0x261] = "@General Game Achievements/General Game Goals/Unlock All Regular Stages",

    -- Special Trophy Requirements
    [0x1B4] = "@General Game Achievements/Special Trophy Requirements/Have Birdo Trophy",
    [0x1B5] = "@General Game Achievements/Special Trophy Requirements/Have Kraid Trophy",
    [0x1B6] = "@General Game Achievements/Special Trophy Requirements/Have Falcon Flyer Trophy",
    [0x1B7] = "@General Game Achievements/Special Trophy Requirements/Have UFO Trophy",
    [0x1B8] = "@General Game Achievements/Special Trophy Requirements/Have Sudowoodo Trophy",
    [0x1CB] = "@General Game Achievements/Special Trophy Requirements/Pikmin Memory Card Data",

    -- VS Match Milestones
    [0x1C4] = "@General Game Achievements/VS Mode Milestones/10 VS. Matches",
    [0x1C5] = "@General Game Achievements/VS Mode Milestones/50 VS. Matches",
    [0x1C6] = "@General Game Achievements/VS Mode Milestones/100 VS. Matches",
    [0x1C7] = "@General Game Achievements/VS Mode Milestones/100 Coin Battles",
    [0x1C8] = "@General Game Achievements/VS Mode Milestones/150 VS. Matches",
    [0x1C9] = "@General Game Achievements/VS Mode Milestones/200 VS. Matches",
    [0x1CA] = "@General Game Achievements/VS Mode Milestones/1000 VS. Matches",
}
